# Account example manifest

apiVersion: v1
kind: Namespace
metadata:
  name: account-ie-test

---
apiVersion: nauth.io/v1alpha1
kind: Account
metadata:
  name: my-account
  namespace: account-ie-test
spec:
  natsClusterRef:
    namespace: nats
    name: local-nats

---
apiVersion: nauth.io/v1alpha1
kind: Account
metadata:
  name: my-other-account
  namespace: account-ie-test
spec:
  natsClusterRef:
    namespace: nats
    name: local-nats
