[env]
NATS_NAMESPACE = "nats"
NATS_VERSION = "2.14.0-alpine"
NACK_VERSION = "0.23.0"
NATS_RELOADER_VERSION = "0.23.0"
NATS_BOX_VERSION = "0.19.5"

[tools]
go = "1.26.3"
python = "3.14.5"
uv = "0.11.16"
ginkgo = "2.31.0"
adr-tools = "3.0.0"
nsc = "2.15.0"
helm = "4.2.1"
kind = "0.32.0"
helm-docs = "1.14.2"
vale = "3.15.1"
"github:elastic/crd-ref-docs" = "0.3.0"
"go:github.com/nats-io/natscli/nats" = "0.4.0"
kubectl-kuttl = "0.26.0"
jq = "1.8.1"

[settings]
experimental = true
disable_tools = ["controller-gen"]

[tasks.go-test]
description = "Run go tests"
dir = "{{ cwd }}"
alias = "gt"
run = "go test ./..."

[tasks."nauth:lint-docs"]
description = "Lint public documentation with Vale"
alias = "nld"
run = "vale README.md www/src/content/docs/index.mdx www/src/content/docs/guides"

[tasks."nauth:e2e-test"]
silent = false
description = "Run end-to-end tests"
run = """
make build-e2e-ctl
PATH="$PWD/bin:$PATH" kubectl kuttl test
"""

[tasks."nauth:kuttle-k9s"]
silent = true
alias = "kk9s"
description = "Run K9s in the test environment (kind)"
run = "KUBECONFIG=kubeconfig k9s"
