{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nauth-metrics-service
  labels:
    service: nauth-metrics-service
spec:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "nauth.name" . }}
{{- end }}
