apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "nauth.name" . }}
  name: account-admin-role
  namespace: {{ include "nauth.namespaceName" . }}
rules:
- apiGroups:
  - nauth.io
  resources:
  - accounts
  verbs:
  - '*'
- apiGroups:
  - nauth.io
  resources:
  - accounts/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "nauth.name" . }}
  name: account-editor-role
  namespace: {{ include "nauth.namespaceName" . }}
rules:
- apiGroups:
  - nauth.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nauth.io
  resources:
  - accounts/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "nauth.name" . }}
  name: account-viewer-role
  namespace: {{ include "nauth.namespaceName" . }}
rules:
- apiGroups:
  - nauth.io
  resources:
  - accounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nauth.io
  resources:
  - accounts/status
  verbs:
  - get
