# AccountExport example manifest

apiVersion: v1
kind: Namespace
metadata:
  name: account-export-test

---
apiVersion: nauth.io/v1alpha1
kind: Account
metadata:
  name: my-account
  namespace: account-export-test
spec:
  natsClusterRef:
    namespace: nats
    name: local-nats

---
apiVersion: nauth.io/v1alpha1
kind: Account
metadata:
  name: my-other-account
  namespace: account-export-test
spec:
  natsClusterRef:
    namespace: nats
    name: local-nats

---
apiVersion: nauth.io/v1alpha1
kind: AccountExport
metadata:
  name: my-account-export
  namespace: account-export-test
spec:
  accountName: my-account
  rules:
    - name: test-rule
      subject: export-account.>
      type: stream
