min_version = "2024.9.5"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

NODE_ENV = "development"

[tools]
bun = "latest"

[tasks."nauth:web:install"]
description = "Install dependencies"
alias = "nwi"
run = "bun install"

[tasks."nauth:web:dev"]
description = "Start development server"
alias = "nwd"
run = "bun run dev"

[tasks."nauth:web:build"]
description = "Build the site"
alias = "nwb"
run = "bun run build"

[tasks."nauth:web:preview"]
description = "Preview built site"
alias = "nwp"
run = "bun run preview"

[tasks."nauth:web:clean"]
description = "Clean node_modules and dist"
run = """
rm -rf node_modules
rm -rf dist
"""

[tasks."nauth:web:lint"]
description = "Lint code with biome"
alias = "nwl"
run = "biome lint ."

[tasks."nauth:web:format"]
description = "Format code with biome"
alias = "nwf"
run = "biome format --write ."

[tasks."nauth:web:check"]
description = "Run biome check (lint + format)"
alias = "nwc"
run = "biome check --write ."
