nats:
  config:
    cluster:
      enabled: true
      replicas: 2
    jetstream:
      enabled: true
      fileStore:
        pvc:
          size: 100Mi
    resolver:
      enabled: true
      merge:
        type: full
        interval: 2m
        timeout: 1.9s
    merge:
      operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJMS0U0WUJSWFNCVExKTk9EM05EMjZWQ1gzUVg1QlM0SjZBSTdLWlhGTU5CRlVRMjZJRllBIiwiaWF0IjoxNzQ5NjI0ODc5LCJpc3MiOiJPQlZSWUNWWjNGVkZNM0hOM1VCTkYzSVRUSExFWlVZN0pOWklEUklKWU1DVzVKVk5FMzNYQTNITCIsInN1YiI6Ik9CVlJZQ1ZaM0ZWRk0zSE4zVUJORjNJVFRITEVaVVk3Sk5aSURSSUpZTUNXNUpWTkUzM1hBM0hMIiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0NSVENPVFpBV1lJTk40VTRYVk5FTTZUREpOT0JMWlFNR0RJWjc2NVdGQTVaTFlNUkIzMkhDRzQiXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.Y_cG7B7I-nJ5ky3FkQZxaVScmhZn1t2xcPalDnAh4EFlgs7CU3RbDJKIvhk5f2sTMB6s6uXAVKaw1KJTlcjaCw
      system_account: AB7CNX7F2BIMEDZIO3A456KQSORYIUIR6RG2WDYSRNRSWMU7LVCBWVX6
      resolver_preload:
        AB7CNX7F2BIMEDZIO3A456KQSORYIUIR6RG2WDYSRNRSWMU7LVCBWVX6: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJaN1VER1FFNUtETU03SVFFVUtBN1pRRE9URzY0TVJQRU1RQUJVU1FFWldCNVM3R000RFFRIiwiaWF0IjoxNzQ5NjI0ODc5LCJpc3MiOiJPQ1JUQ09UWkFXWUlOTjRVNFhWTkVNNlRESk5PQkxaUU1HRElaNzY1V0ZBNVpMWU1SQjMySENHNCIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQjdDTlg3RjJCSU1FRFpJTzNBNDU2S1FTT1JZSVVJUjZSRzJXRFlTUk5SU1dNVTdMVkNCV1ZYNiIsIm5hdHMiOnsiZXhwb3J0cyI6W3sibmFtZSI6ImFjY291bnQtbW9uaXRvcmluZy1zdHJlYW1zIiwic3ViamVjdCI6IiRTWVMuQUNDT1VOVC4qLlx1MDAzZSIsInR5cGUiOiJzdHJlYW0iLCJhY2NvdW50X3Rva2VuX3Bvc2l0aW9uIjozfSx7Im5hbWUiOiJhY2NvdW50LW1vbml0b3Jpbmctc2VydmljZXMiLCJzdWJqZWN0IjoiJFNZUy5SRVEuQUNDT1VOVC4qLioiLCJ0eXBlIjoic2VydmljZSIsInJlc3BvbnNlX3R5cGUiOiJTdHJlYW0iLCJhY2NvdW50X3Rva2VuX3Bvc2l0aW9uIjo0fV0sImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xfSwic2lnbmluZ19rZXlzIjpbIkFCSE9TNlZITlQ3Uk4ySkNPTUlWNk1UNDVYRVYyQ1Q0TlVBWTRNNDJFUFlGT1RRTUxQSVc0V1RSIl0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sImF1dGhvcml6YXRpb24iOnt9LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.BcfwA7gy6G4rc9Zhtjr43nyjGvgerMfPhqxQdlForgZMrqQtvpXlX5WlXWAhpl90G2DYLbKaDiph6-FBwdjoBg

  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule

  promExporter:
    enabled: false
    podMonitor:
      enabled: false

  container:
    env:
      # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
      # should be ~90% of memory limit
      GOMEMLIMIT: 900MiB
    merge:
      # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
      # resources:
      #   requests:
      #     cpu: "2"
      #     memory: 8Gi
      #   limits:
      #     cpu: "2"
      #     memory: 8Gi
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 100Mi

nack:
  nameOverride: nack
  jetstream:
    nats:
      url: nats://nats.nats.svc.cluster.local:4222
    additionalArgs:
      - --crd-connect
      - --control-loop
